import { drizzle } from "drizzle-orm/postgres-js";
import { migrate } from "drizzle-orm/postgres-js/migrator";
import postgres from "postgres";

/**
 * Run Drizzle migrations against the given database URL.
 * Uses the SQL files generated by `drizzle-kit generate`.
 */
export async function runMigrations(databaseUrl: string): Promise<void> {
  console.log("[migrations] Running database migrations...");

  const migrationClient = postgres(databaseUrl, {
    max: 1,
    onnotice: () => {},  // Suppress NOTICE messages (e.g. "already exists, skipping")
  });
  const db = drizzle(migrationClient);

  try {
    await migrate(db, { migrationsFolder: "./drizzle" });
    console.log("[migrations] Migrations complete");
  } catch (error) {
    console.error("[migrations] Migration failed:", error);
    throw error;
  } finally {
    await migrationClient.end();
  }
}
