#!/usr/bin/env bash
# =============================================================================
# CPI Connect — First-Time Setup Script
# =============================================================================
# Generates all required secrets, writes .env, and starts the full stack.
#
# Usage:
#   bash docker/setup.sh
#
# Prerequisites: docker, docker compose, openssl, node
# =============================================================================
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"

cd "$PROJECT_DIR"

echo "============================================="
echo "  CPI Connect — Self-Hosted Setup"
echo "============================================="
echo ""

# ── Check prerequisites ──────────────────────────────────────────────────
command -v docker >/dev/null 2>&1 || { echo "ERROR: docker is required. Install from https://docs.docker.com/get-docker/"; exit 1; }
command -v openssl >/dev/null 2>&1 || { echo "ERROR: openssl is required."; exit 1; }
command -v node >/dev/null 2>&1 || { echo "ERROR: node is required for JWT key generation."; exit 1; }

# ── Generate secrets ─────────────────────────────────────────────────────
echo "[1/4] Generating secrets..."

POSTGRES_PASSWORD=$(openssl rand -hex 16)
ENCRYPTION_KEY=$(openssl rand -base64 32)
CRON_SECRET=$(openssl rand -hex 16)
LITELLM_MASTER_KEY="sk-$(openssl rand -hex 20)"
SUPABASE_JWT_SECRET=$(openssl rand -hex 32)

# Generate Supabase ANON key
ANON_KEY=$(node -e "
const crypto = require('crypto');
const h = Buffer.from(JSON.stringify({alg:'HS256',typ:'JWT'})).toString('base64url');
const now = Math.floor(Date.now()/1000);
const p = Buffer.from(JSON.stringify({role:'anon',iss:'supabase',iat:now,exp:now+315360000})).toString('base64url');
const s = crypto.createHmac('sha256','$SUPABASE_JWT_SECRET').update(h+'.'+p).digest('base64url');
console.log(h+'.'+p+'.'+s);
")

# Generate Supabase SERVICE_ROLE key
SERVICE_KEY=$(node -e "
const crypto = require('crypto');
const h = Buffer.from(JSON.stringify({alg:'HS256',typ:'JWT'})).toString('base64url');
const now = Math.floor(Date.now()/1000);
const p = Buffer.from(JSON.stringify({role:'service_role',iss:'supabase',iat:now,exp:now+315360000})).toString('base64url');
const s = crypto.createHmac('sha256','$SUPABASE_JWT_SECRET').update(h+'.'+p).digest('base64url');
console.log(h+'.'+p+'.'+s);
")

echo "       Secrets generated."

# ── Write .env file ──────────────────────────────────────────────────────
echo "[2/4] Writing .env file..."

if [ -f .env ]; then
  BACKUP=".env.backup.$(date +%Y%m%d%H%M%S)"
  cp .env "$BACKUP"
  echo "       Existing .env backed up to $BACKUP"
fi

cat > .env <<EOF
# =============================================================================
# CPI Connect — Environment Configuration
# Generated by docker/setup.sh on $(date -u +"%Y-%m-%d %H:%M:%S UTC")
# =============================================================================

# ── Database ─────────────────────────────────────────────────────────────
POSTGRES_PASSWORD=$POSTGRES_PASSWORD
POSTGRES_DB=cpiconnect

# ── Supabase ─────────────────────────────────────────────────────────────
SUPABASE_JWT_SECRET=$SUPABASE_JWT_SECRET
NEXT_PUBLIC_SUPABASE_URL=http://localhost:8000
NEXT_PUBLIC_SUPABASE_ANON_KEY=$ANON_KEY
SUPABASE_SERVICE_ROLE_KEY=$SERVICE_KEY

# ── Encryption & Auth ────────────────────────────────────────────────────
ENCRYPTION_KEY=$ENCRYPTION_KEY
CRON_SECRET=$CRON_SECRET

# ── Application ──────────────────────────────────────────────────────────
NEXT_PUBLIC_APP_URL=http://localhost:3000
NEXT_PUBLIC_DEPLOYMENT_MODE=self-hosted

# ── Ports ────────────────────────────────────────────────────────────────
APP_PORT=3000
SUPABASE_PORT=8000
STUDIO_PORT=3100
LITELLM_PORT=4000
DB_PORT=5433

# ── AI Provider (LiteLLM Proxy) ─────────────────────────────────────────
AI_PROVIDER=llmlite
LITELLM_MASTER_KEY=$LITELLM_MASTER_KEY

# Uncomment and set API keys for your preferred LLM provider:
# OPENAI_API_KEY=sk-...
# ANTHROPIC_API_KEY=sk-ant-...
# GOOGLE_API_KEY=AIza...

# ── Optional: Self-Hosted Limits (default: unlimited) ───────────────────
# SELF_HOSTED_AI_CALLS_LIMIT=1000
# SELF_HOSTED_MAX_TENANTS=
# SELF_HOSTED_MAX_IFLOWS=
# SELF_HOSTED_MAX_MEMBERS=
EOF

echo "       .env written."

# ── Print summary ────────────────────────────────────────────────────────
echo "[3/4] Configuration summary:"
echo ""
echo "  App URL:        http://localhost:3000"
echo "  Supabase API:   http://localhost:8000"
echo "  Supabase Studio: http://localhost:3100"
echo "  LiteLLM Proxy:  http://localhost:4000"
echo "  PostgreSQL:     localhost:5433"
echo ""
echo "  IMPORTANT: Edit docker/litellm-config.yaml to configure your AI models."
echo "  IMPORTANT: Set at least one LLM API key in .env (OPENAI_API_KEY, etc.)"
echo ""

# ── Start the stack ──────────────────────────────────────────────────────
echo "[4/4] Starting CPI Connect..."
docker compose -f docker-compose.selfhost.yml up -d

echo ""
echo "============================================="
echo "  CPI Connect is starting!"
echo "============================================="
echo ""
echo "  Wait 30-60 seconds for all services to initialize."
echo "  Then open: http://localhost:3000/setup"
echo "  to create your admin account."
echo ""
echo "  View logs:  docker compose -f docker-compose.selfhost.yml logs -f app"
echo "  Stop:       docker compose -f docker-compose.selfhost.yml down"
echo ""
