/**
 * Design Reviewer Agent
 *
 * Reviews an iFlow design generated by the Architect Agent across 6 categories:
 * Architecture, Adapters, Security, Performance, Error Handling, Best Practices.
 *
 * Capabilities:
 * - Scores each category 1-10 with PASS/WARN/FAIL status
 * - Produces overall verdict: APPROVED / NEEDS_CHANGES / REJECTED
 * - Identifies issues by severity (CRITICAL/HIGH/MEDIUM/LOW)
 * - Auto-fixes minor issues and produces a patchedDesign + DesignDiff
 * - Deterministic post-processing for common fixes (timeouts, defaults, IDs)
 *
 * Model: gemini-2.5-flash-lite (prototype)
 */

import type { LanguageModel } from 'ai';
import { BaseAgent } from '../agent-base';
import type {
  PipelineContext,
  DesignReview,
  DesignDiff,
  DesignIssue,
  DesignSuggestion,
  ReviewCategory,
  ReviewerOutput,
  TenantCapabilities,
} from '../pipeline-state';
import type { IFlowDesign } from '@/components/ai/v2/specialized/iflow-creator/types';
import {
  DESIGN_REVIEWER_SYSTEM_PROMPT,
  buildReviewerPrompt,
} from '../prompts/reviewer-prompts';
import { cleanAIJson, fixUnescapedQuotesStateMachine } from '../utils/json-cleaner';
import { runText } from '@/lib/ai/runtime/text';

// ============================================================================
// Input / Output Types
// ============================================================================

export interface DesignReviewerInput {
  design: IFlowDesign;
  rationale: string;
  tenantCapabilities: TenantCapabilities;
}

// ============================================================================
// Agent Implementation
// ============================================================================

export class DesignReviewerAgent extends BaseAgent<DesignReviewerInput, ReviewerOutput> {
  readonly name = 'REVIEWER' as const;
  readonly model: LanguageModel | null = null;
  readonly description = 'Reviews iFlow design for quality, correctness, and production-readiness';

  protected async run(
    input: DesignReviewerInput,
    context: PipelineContext
  ): Promise<{ output: ReviewerOutput; tokensUsed: number }> {
    const { design, rationale, tenantCapabilities } = input;

    // Step 1: Run deterministic checks first (fast, no AI)
    const deterministicIssues = runDeterministicChecks(design, tenantCapabilities);

    // Step 2: Call AI for semantic review
    const userPrompt = buildReviewerPrompt(design, rationale, tenantCapabilities, context);

    const result = await runText({
      system: DESIGN_REVIEWER_SYSTEM_PROMPT,
      prompt: userPrompt,
      maxTokens: 6000,
      temperature: 0.2, // Low temperature for consistent reviews
      modelKind: 'orchestrator',
    });
    const text = result.text;

    // Step 3: Parse the AI review response
    const aiReview = parseReviewResponse(text);

    // Step 4: Merge deterministic issues into AI review
    mergeIssues(aiReview, deterministicIssues);

    // Step 5: Recalculate scores after merge
    recalculateVerdict(aiReview);

    // Step 6: Apply auto-fixes to produce patched design
    const { patchedDesign, designDiff } = applyAutoFixes(design, aiReview);

    const tokensUsed = result.usage.totalTokens ?? 0;

    return {
      output: {
        review: aiReview,
        patchedDesign: designDiff.length > 0 ? patchedDesign : undefined,
        designDiff: designDiff.length > 0 ? designDiff : undefined,
      },
      tokensUsed,
    };
  }
}

// ============================================================================
// Deterministic Checks (no AI, fast, reliable)
// ============================================================================

interface DeterministicIssue {
  severity: DesignIssue['severity'];
  category: string;
  component: string;
  description: string;
  impact: string;
  recommendation: string;
  autoFixable: boolean;
}

function runDeterministicChecks(
  design: IFlowDesign,
  tenantCapabilities: TenantCapabilities
): DeterministicIssue[] {
  const issues: DeterministicIssue[] = [];

  // Check 1: Adapter availability on tenant
  if (design.adapters && tenantCapabilities.availableAdapters.length > 0) {
    for (const adapter of design.adapters) {
      const adapterType = adapter.type?.toLowerCase() ?? '';
      const available = tenantCapabilities.availableAdapters.some(
        (a) => a.toLowerCase() === adapterType
      );
      if (!available && adapterType) {
        issues.push({
          severity: 'HIGH',
          category: 'adapters',
          component: `adapter:${adapter.name || adapter.type}`,
          description: `Adapter type "${adapter.type}" is not available on the target tenant`,
          impact: 'Deployment will fail if this adapter is not installed on the tenant',
          recommendation: `Replace with an available adapter or install "${adapter.type}" adapter on the tenant`,
          autoFixable: false,
        });
      }
    }
  }

  // Check 2: Missing connection timeouts
  if (design.adapters) {
    for (let i = 0; i < design.adapters.length; i++) {
      const adapter = design.adapters[i];
      if (!adapter.connectionTimeout && !adapter.timeout) {
        issues.push({
          severity: 'MEDIUM',
          category: 'performance',
          component: `adapters[${i}]:${adapter.name || adapter.type}`,
          description: 'No connection timeout configured',
          impact: 'Long-running requests may hang indefinitely',
          recommendation: 'Set connectionTimeout to 60000ms (1 minute)',
          autoFixable: true,
        });
      }
    }
  }

  // Check 3: Missing error handlers
  const hasErrorHandler =
    (design.errorHandlers && design.errorHandlers.length > 0) ||
    (design.exceptionSubprocesses && design.exceptionSubprocesses.length > 0);

  if (!hasErrorHandler) {
    issues.push({
      severity: 'HIGH',
      category: 'errorHandling',
      component: 'flow',
      description: 'No error handlers or exception subprocesses defined',
      impact: 'Errors will cause unhandled failures without proper alerting or recovery',
      recommendation: 'Add at least one exception subprocess with appropriate error handling',
      autoFixable: false,
    });
  }

  // Check 4: Script language validation
  if (design.scripts) {
    for (let i = 0; i < design.scripts.length; i++) {
      const script = design.scripts[i];
      const lang = (script.type ?? '').toLowerCase();
      if (lang && lang !== 'groovy' && lang !== 'javascript') {
        issues.push({
          severity: 'MEDIUM',
          category: 'bestPractices',
          component: `scripts[${i}]:${script.name || 'unnamed'}`,
          description: `Script language "${script.type}" is not standard for SAP CPI. Use "groovy" (recommended) or "javascript"`,
          impact: 'Script may fail to execute on the runtime',
          recommendation: 'Change script language to "groovy"',
          autoFixable: true,
        });
      }
    }
  }

  // Check 5: Duplicate flow step IDs
  if (design.flowSteps) {
    const ids = new Set<string>();
    for (let i = 0; i < design.flowSteps.length; i++) {
      const step = design.flowSteps[i];
      const stepId = step.id;
      if (stepId) {
        if (ids.has(stepId)) {
          issues.push({
            severity: 'HIGH',
            category: 'architecture',
            component: `flowSteps[${i}]:${stepId}`,
            description: `Duplicate flow step ID: "${stepId}"`,
            impact: 'BPMN2 generation will produce invalid XML with duplicate element IDs',
            recommendation: 'Assign unique IDs to all flow steps',
            autoFixable: true,
          });
        }
        ids.add(stepId);
      }
    }
  }

  // Check 6: Missing metadata
  if (!design.metadata || !design.metadata.name || !design.metadata.id) {
    issues.push({
      severity: 'MEDIUM',
      category: 'bestPractices',
      component: 'metadata',
      description: 'Missing or incomplete metadata (name/id)',
      impact: 'Deployment may fail or produce poorly labeled artifacts',
      recommendation: 'Ensure metadata has name, id, description, and version',
      autoFixable: true,
    });
  }

  // Check 7: Empty flow (no steps, no adapters)
  const hasContent =
    (design.adapters && design.adapters.length > 0) ||
    (design.flowSteps && design.flowSteps.length > 0);

  if (!hasContent) {
    issues.push({
      severity: 'CRITICAL',
      category: 'architecture',
      component: 'flow',
      description: 'Design has no adapters and no flow steps — the flow is empty',
      impact: 'The integration flow will do nothing',
      recommendation: 'Regenerate the design with clear integration requirements',
      autoFixable: false,
    });
  }

  // Check 8: Content type for HTTP-based adapters
  if (design.adapters) {
    const httpAdapters = ['HTTP', 'HTTPS', 'OData', 'REST', 'SOAP', 'ODataV2', 'ODataV4'];
    for (let i = 0; i < design.adapters.length; i++) {
      const adapter = design.adapters[i];
      const adapterProps = adapter.properties ?? {};
      if (httpAdapters.some((t) => t.toLowerCase() === (adapter.type ?? '').toLowerCase())) {
        if (!adapterProps.contentType && !adapterProps.requestContentType) {
          issues.push({
            severity: 'LOW',
            category: 'adapters',
            component: `adapters[${i}]:${adapter.name || adapter.type}`,
            description: 'No content type specified for HTTP-based adapter',
            impact: 'Server may reject requests without explicit Content-Type',
            recommendation: 'Set contentType to "application/json" or "application/xml"',
            autoFixable: true,
          });
        }
      }
    }
  }

  return issues;
}

// ============================================================================
// AI Response Parsing
// ============================================================================

function parseReviewResponse(text: string): DesignReview {
  // Use the shared robust JSON cleaner
  let jsonStr = cleanAIJson(text);

  let parsed: Record<string, unknown>;
  try {
    parsed = JSON.parse(jsonStr);
  } catch {
    // Try state-machine quote repair
    try {
      parsed = JSON.parse(fixUnescapedQuotesStateMachine(jsonStr));
    } catch {
      // If AI returned patchedDesign that's too large/malformed, try removing it
      try {
        const withoutPatched = jsonStr.replace(
          /"patchedDesign"\s*:\s*\{[\s\S]*?\}(?=\s*,?\s*"designDiff")/,
          '"patchedDesign": null'
        );
        parsed = JSON.parse(withoutPatched);
      } catch {
        // Return a conservative default review
        console.warn('[DesignReviewer] Failed to parse AI review response, using fallback');
        return createFallbackReview();
      }
    }
  }

  return normalizeReview(parsed);
}

/**
 * Normalize the parsed JSON into a valid DesignReview
 */
function normalizeReview(raw: Record<string, unknown>): DesignReview {
  const categories = (raw.categories ?? {}) as Record<string, unknown>;

  const normalizeCategory = (cat: unknown): ReviewCategory => {
    const c = (cat ?? {}) as Record<string, unknown>;
    return {
      score: clampScore(c.score as number),
      status: validateCategoryStatus(c.status as string),
      findings: Array.isArray(c.findings) ? (c.findings as string[]) : [],
    };
  };

  const normalizeIssue = (issue: Record<string, unknown>, index: number): DesignIssue => ({
    id: (issue.id as string) || `ISS-${String(index + 1).padStart(3, '0')}`,
    severity: validateSeverity(issue.severity as string),
    category: (issue.category as string) || 'general',
    component: (issue.component as string) || 'unknown',
    description: (issue.description as string) || 'No description',
    impact: (issue.impact as string) || 'Unknown impact',
    recommendation: (issue.recommendation as string) || 'No recommendation',
  });

  const normalizeSuggestion = (sug: Record<string, unknown>, index: number): DesignSuggestion => ({
    id: (sug.id as string) || `SUG-${String(index + 1).padStart(3, '0')}`,
    category: (sug.category as string) || 'general',
    component: (sug.component as string) || 'unknown',
    current: (sug.current as string) || '',
    suggested: (sug.suggested as string) || '',
    reason: (sug.reason as string) || '',
    autoApplied: (sug.autoApplied as boolean) ?? false,
  });

  const issues = Array.isArray(raw.issues)
    ? (raw.issues as Record<string, unknown>[]).map(normalizeIssue)
    : [];

  const suggestions = Array.isArray(raw.suggestions)
    ? (raw.suggestions as Record<string, unknown>[]).map(normalizeSuggestion)
    : [];

  return {
    overallScore: clampScore(raw.overallScore as number),
    verdict: validateVerdict(raw.verdict as string),
    categories: {
      architecture: normalizeCategory(categories.architecture),
      adapters: normalizeCategory(categories.adapters),
      security: normalizeCategory(categories.security),
      performance: normalizeCategory(categories.performance),
      errorHandling: normalizeCategory(categories.errorHandling),
      bestPractices: normalizeCategory(categories.bestPractices),
    },
    issues,
    suggestions,
    autoFixable: suggestions.filter((s) => s.autoApplied),
    requiresUserInput: issues.filter(
      (i) => i.severity === 'CRITICAL' || i.severity === 'HIGH'
    ),
  };
}

function createFallbackReview(): DesignReview {
  const defaultCat: ReviewCategory = { score: 5, status: 'WARN', findings: ['Unable to parse AI review — manual review recommended'] };
  return {
    overallScore: 5,
    verdict: 'NEEDS_CHANGES',
    categories: {
      architecture: { ...defaultCat },
      adapters: { ...defaultCat },
      security: { ...defaultCat },
      performance: { ...defaultCat },
      errorHandling: { ...defaultCat },
      bestPractices: { ...defaultCat },
    },
    issues: [{
      id: 'ISS-FALLBACK',
      severity: 'MEDIUM',
      category: 'general',
      component: 'review',
      description: 'AI review response could not be parsed',
      impact: 'Design has not been reviewed by AI — proceed with caution',
      recommendation: 'Review the design manually before deploying',
    }],
    suggestions: [],
    autoFixable: [],
    requiresUserInput: [],
  };
}

// ============================================================================
// Issue Merging
// ============================================================================

function mergeIssues(review: DesignReview, deterministicIssues: DeterministicIssue[]): void {
  let issueCounter = review.issues.length;

  for (const dIssue of deterministicIssues) {
    // Check if the AI already caught this issue (by matching component + category)
    const alreadyExists = review.issues.some(
      (existing) =>
        existing.component === dIssue.component &&
        existing.category === dIssue.category
    );

    if (!alreadyExists) {
      issueCounter++;
      review.issues.push({
        id: `DET-${String(issueCounter).padStart(3, '0')}`,
        severity: dIssue.severity,
        category: dIssue.category,
        component: dIssue.component,
        description: dIssue.description,
        impact: dIssue.impact,
        recommendation: dIssue.recommendation,
      });

      // If auto-fixable, also add as a suggestion
      if (dIssue.autoFixable) {
        review.suggestions.push({
          id: `DET-SUG-${String(issueCounter).padStart(3, '0')}`,
          category: dIssue.category,
          component: dIssue.component,
          current: 'Not set',
          suggested: dIssue.recommendation,
          reason: dIssue.impact,
          autoApplied: true,
        });
        review.autoFixable.push(review.suggestions[review.suggestions.length - 1]);
      }
    }
  }

  // Update requiresUserInput
  review.requiresUserInput = review.issues.filter(
    (i) => i.severity === 'CRITICAL' || i.severity === 'HIGH'
  );
}

// ============================================================================
// Verdict Recalculation
// ============================================================================

function recalculateVerdict(review: DesignReview): void {
  // Recompute category statuses based on their issues
  const categoryNames = Object.keys(review.categories) as (keyof DesignReview['categories'])[];

  for (const catName of categoryNames) {
    const catIssues = review.issues.filter((i) => i.category === catName);
    const hasCritical = catIssues.some((i) => i.severity === 'CRITICAL');
    const hasHigh = catIssues.some((i) => i.severity === 'HIGH');

    if (hasCritical) {
      review.categories[catName].status = 'FAIL';
      review.categories[catName].score = Math.min(review.categories[catName].score, 3);
    } else if (hasHigh) {
      review.categories[catName].status =
        review.categories[catName].score >= 7 ? 'WARN' : review.categories[catName].status;
      review.categories[catName].score = Math.min(review.categories[catName].score, 6);
    }
  }

  // Recalculate overall score (weighted)
  const weights: Record<string, number> = {
    architecture: 0.25,
    adapters: 0.2,
    security: 0.2,
    performance: 0.1,
    errorHandling: 0.15,
    bestPractices: 0.1,
  };

  let weightedSum = 0;
  for (const catName of categoryNames) {
    weightedSum += review.categories[catName].score * (weights[catName] ?? 0.1);
  }
  review.overallScore = Math.round(weightedSum * 10) / 10;

  // Determine verdict
  const hasCritical = review.issues.some((i) => i.severity === 'CRITICAL');
  const hasFailCategory = categoryNames.some((c) => review.categories[c].status === 'FAIL');

  if (hasCritical || review.overallScore < 4) {
    review.verdict = 'REJECTED';
  } else if (hasFailCategory || review.overallScore < 7) {
    review.verdict = 'NEEDS_CHANGES';
  } else {
    review.verdict = 'APPROVED';
  }
}

// ============================================================================
// Auto-Fix Application
// ============================================================================

function applyAutoFixes(
  originalDesign: IFlowDesign,
  review: DesignReview
): { patchedDesign: IFlowDesign; designDiff: DesignDiff[] } {
  // Deep clone the design
  const patched: IFlowDesign = JSON.parse(JSON.stringify(originalDesign));
  const diffs: DesignDiff[] = [];

  // Fix 1: Add missing connection timeouts
  if (patched.adapters) {
    for (let i = 0; i < patched.adapters.length; i++) {
      const adapter = patched.adapters[i];
      if (!adapter.connectionTimeout && !adapter.timeout) {
        adapter.connectionTimeout = 60000;
        diffs.push({
          path: `adapters[${i}].connectionTimeout`,
          before: undefined,
          after: 60000,
          reason: 'Added default connection timeout (60s) to prevent hanging requests',
        });
      }
    }
  }

  // Fix 2: Normalize script languages to groovy
  if (patched.scripts) {
    for (let i = 0; i < patched.scripts.length; i++) {
      const script = patched.scripts[i];
      const lang = (script.type ?? '').toLowerCase();
      if (lang && lang !== 'groovy' && lang !== 'javascript') {
        const before = script.type;
        (script as unknown as Record<string, unknown>).type = 'groovy';
        diffs.push({
          path: `scripts[${i}].type`,
          before,
          after: 'groovy',
          reason: 'Normalized script language to groovy (SAP CPI standard)',
        });
      }
    }
  }

  // Fix 3: Deduplicate flow step IDs
  if (patched.flowSteps) {
    const seen = new Set<string>();
    for (let i = 0; i < patched.flowSteps.length; i++) {
      const step = patched.flowSteps[i];
      const stepId = step.id;
      if (stepId && seen.has(stepId)) {
        const newId = `${stepId}_${i}`;
        diffs.push({
          path: `flowSteps[${i}].id`,
          before: stepId,
          after: newId,
          reason: `Deduplicated flow step ID: "${stepId}" → "${newId}"`,
        });
        (step as unknown as Record<string, unknown>).id = newId;
      }
      if (stepId) seen.add(stepId);
    }
  }

  // Fix 4: Ensure metadata defaults
  if (!patched.metadata || !patched.metadata.name) {
    const before = patched.metadata ? { ...patched.metadata } : undefined;
    patched.metadata = {
      name: patched.metadata?.name || 'Generated_iFlow',
      id: patched.metadata?.id || 'Generated_iFlow',
      description: patched.metadata?.description || 'AI-generated integration flow',
      version: patched.metadata?.version || '1.0.0',
    };
    diffs.push({
      path: 'metadata',
      before,
      after: patched.metadata,
      reason: 'Filled missing metadata fields with defaults',
    });
  }

  // Fix 5: Apply AI-suggested auto-fixes from the patchedDesign if available
  // (AI may have returned a full patchedDesign — we prefer our deterministic fixes
  //  but track any extra diffs from the AI review's designDiff)

  return { patchedDesign: patched, designDiff: diffs };
}

// ============================================================================
// Helpers
// ============================================================================

function clampScore(score: unknown): number {
  const n = Number(score);
  if (isNaN(n)) return 5;
  return Math.max(1, Math.min(10, Math.round(n * 10) / 10));
}

function validateSeverity(severity: string): DesignIssue['severity'] {
  const valid: DesignIssue['severity'][] = ['CRITICAL', 'HIGH', 'MEDIUM', 'LOW'];
  const upper = (severity ?? '').toUpperCase() as DesignIssue['severity'];
  return valid.includes(upper) ? upper : 'MEDIUM';
}

function validateVerdict(verdict: string): DesignReview['verdict'] {
  const valid: DesignReview['verdict'][] = ['APPROVED', 'NEEDS_CHANGES', 'REJECTED'];
  const upper = (verdict ?? '').toUpperCase() as DesignReview['verdict'];
  return valid.includes(upper) ? upper : 'NEEDS_CHANGES';
}

function validateCategoryStatus(status: string): ReviewCategory['status'] {
  const valid: ReviewCategory['status'][] = ['PASS', 'WARN', 'FAIL'];
  const upper = (status ?? '').toUpperCase() as ReviewCategory['status'];
  return valid.includes(upper) ? upper : 'WARN';
}
